上课的跟练,没啥别的

In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
#*from matplotlib.patches import Ellipse , Rectangle
import numpy as np
import pandas as pd

import torch

#*----------------------------------------------------------------
mpl.rcParams['font.sans-serif'] = ['SimHei'] # *允许显示中文
plt.rcParams['axes.unicode_minus']=False# *允许显示坐标轴负数
#*----------------------------------------------------------------

params = {'legend.fontsize': 7,}

plt.rcParams.update(params)

In [8]:
data = np.array([[1,2,3,4] , [1.3 , 1.4 , 1.5 , 1.3]])
t_data = torch.from_numpy(data)
t_data

tensor([[1.0000, 2.0000, 3.0000, 4.0000],
        [1.3000, 1.4000, 1.5000, 1.3000]], dtype=torch.float64)

In [18]:
print(torch.rand_like(t_data))
print(torch.ones_like(t_data))

tensor([[0.7089, 0.1376, 0.2124, 0.3155],
        [0.4882, 0.9635, 0.2635, 0.7184]], dtype=torch.float64)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


可以互相转换

In [27]:
print(torch.rand((1,2)))
print(torch.ones((3,4)))
print(torch.zeros(5))
print(np.array(torch.zeros((3,3))))

tensor([[0.3679, 0.5522]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([0., 0., 0., 0., 0.])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
print(t_data.shape)
print(t_data.dtype)
print(t_data.device)

torch.Size([2, 4])
torch.float64
cpu
